name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Testing:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Get dependencies
        run: go get
      - run: go get -u golang.org/x/lint/golint

      - name: Go lint
        run: golint -set_exit_status $(go list ./... | grep -v /vendor/)

      # - name: Test
      #   run: go test -v ./...

  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Get dependencies
        run: go get

      - name: Build
        run: go build

      - uses: actions/checkout@v2

      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world.txt

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact/dllInjection.exe
